---
# tasks file for hswong3i.bitbucket

- name: create group
  group:
    name: "{{ bitbucket_user }}"
    gid: "{{ bitbucket_gid | default(None) or omit }}"
  when: bitbucket_pass is string and bitbucket_hash_salt is string
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: create user
  user:
    name: "{{ bitbucket_user }}"
    password: "{{ bitbucket_pass | password_hash('sha512', bitbucket_hash_salt) }}"
    home: "{{ bitbucket_home }}"
    group: "{{ bitbucket_user }}"
    uid: "{{ bitbucket_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: bitbucket_pass is string and bitbucket_hash_salt is string
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: ensure pre-req packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ bitbucket_packages }}"

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ bitbucket_catalina }}", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0755", state: "directory" }
    - { dest: "{{ bitbucket_home }}/shared", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0755", state: "directory" }
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: download package
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
  with_items:
    - { url: "{{ bitbucket_url }}", dest: "/tmp/{{ bitbucket_archive }}", checksum: "{{ bitbucket_checksum }}" }
  tags: hswong3i.bitbucket

- name: unarchive package
  shell: |
    tar zxvf /tmp/{{ bitbucket_archive }} -C {{ bitbucket_catalina }} --strip-components=1
    chown -Rf {{ bitbucket_user }}:{{ bitbucket_user }} {{ bitbucket_catalina }}
  args:
    creates: "{{ bitbucket_catalina }}/bin/start-bitbucket.sh"
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/init.d/bitbucket.j2", dest: "/etc/init.d/bitbucket", owner: "root", group: "root", mode: "0755" }
    - { src: "usr/share/bitbucket/bin/_start-webapp.sh.j2", dest: "{{ bitbucket_catalina }}/bin/_start-webapp.sh", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0755" }
    - { src: "usr/share/bitbucket/bin/set-bitbucket-home.sh.j2", dest: "{{ bitbucket_catalina }}/bin/set-bitbucket-home.sh", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0755" }
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: create bitbucket.properties
  copy:
    content: ""
    dest: "{{ bitbucket_home }}/shared/bitbucket.properties"
    force: "no"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_user }}"
    mode: "0644"
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: configure bitbucket.properties
  lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.context-path=", line: "server.context-path={{ bitbucket_context_path }}", state: "present" }
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.port=", line: "server.port={{ bitbucket_connector_port }}", state: "present" }
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: configure bitbucket.properties (HTTP reverse proxy)
  lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.proxy-name=", line: "server.proxy-name={{ bitbucket_proxy_name }}", state: "present" }
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.proxy-port=", line: "server.proxy-port=80", state: "present" }
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.scheme=", line: "server.scheme={{ bitbucket_scheme }}", state: "present" }
  when:
    - bitbucket_proxy_name != none
    - bitbucket_scheme == "http"
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: configure bitbucket.properties (HTTPS reverse proxy)
  lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.proxy-name=", line: "server.proxy-name={{ bitbucket_proxy_name }}", state: "present" }
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.proxy-port=", line: "server.proxy-port=443", state: "present" }
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.scheme=", line: "server.scheme={{ bitbucket_scheme }}", state: "present" }
    - { path: "{{ bitbucket_home }}/shared/bitbucket.properties", regexp: "^server.secure=", line: "server.secure=true", state: "present" }
  when:
    - bitbucket_proxy_name != none
    - bitbucket_scheme == "https"
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: enable service
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: "bitbucket", enabled: "yes" }
  notify: restart bitbucket
  tags: hswong3i.bitbucket
